service: adi-lambda-puppeteer2

custom:
  envName: '${self:provider.stage}'
  apigwBinary:
    types:
      - '*/*'


provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  timeout: 900
  memorySize: 1024
  provisionedConcurrency: 3
  reservedConcurrency: 5
  environment:
    APPLICATION_NAME: lambda-puppeteer2
    PDF_BUCKET: adi-sec-demo

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:provider.environment.PDF_BUCKET}/*"

plugins:
  - serverless-apigw-binary
  - serverless-apigwy-binary

functions:
  post:
    handler: dist/lambda/html2pdf.handler
    events:
      - http: POST html2pdf
  get:
    handler: dist/lambda/pdf-downloader.handler
    events:
      - http:
          method: GET
          path: pdfdownloader
          contentHandling: CONVERT_TO_BINARY

package:
  exclude:
    - .idea/**
    - build/**
    - src/**
    - test/**
    - artifacts/**
    - combined.log
    - error.log
    - node_modules/puppeteer/.local-chromium/**


